# Generated by Django 5.0.3 on 2024-03-14 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fill_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='sex',
            field=models.CharField(choices=[(None, ''), ('M', 'Male'), ('F', 'Female')], help_text='Student sex', max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='text',
            name='student_number',
            field=models.IntegerField(help_text='Number of the student writer of this text', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='text',
            name='type',
            field=models.CharField(choices=[(None, ''), ('SPOKEN', 'Spoken'), ('WRITTEN', 'Written'), ('NOTEBOOKS', 'Notebooks')], help_text='Type of the text', max_length=10, verbose_name='Type'),
        ),
    ]
