# Generated by Django 5.0.3 on 2024-03-14 08:27

from django.db import migrations
from django.db.migrations import RunPython


def create_administrator(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create_superuser('administrator', '', 'abdulaziz')


def reverse_create_administrator(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.get(username='administrator').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_text_sex_alter_text_student_number_and_more'),
    ]

    operations = [
        RunPython(create_administrator, reverse_create_administrator),
    ]
