# Generated by Django 5.0.3 on 2024-03-17 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_create_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='city',
            field=models.CharField(help_text='City of the student', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='text',
            name='level',
            field=models.IntegerField(help_text='Level of the student', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='text',
            name='school',
            field=models.CharField(help_text='School of the student', max_length=100, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='text',
            name='student_number',
            field=models.IntegerField(help_text='Number of the student', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number'),
        ),
    ]
