# Generated by Django 5.0.3 on 2024-03-30 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_text_city_alter_text_level_alter_text_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='city',
            field=models.CharField(blank=True, help_text='City of the student', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='text',
            name='level',
            field=models.IntegerField(blank=True, help_text='Level of the student', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='text',
            name='school',
            field=models.CharField(blank=True, help_text='School of the student', max_length=100, null=True, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='text',
            name='sex',
            field=models.CharField(choices=[(None, 'Unspecified'), ('M', 'Male'), ('F', 'Female')], help_text='Student sex', max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='text',
            name='type',
            field=models.CharField(choices=[(None, 'Unspecified'), ('SPOKEN', 'Spoken'), ('WRITTEN', 'Written'), ('NOTEBOOKS', 'Notebooks')], help_text='Type of the text', max_length=10, verbose_name='Type'),
        ),
    ]
