# Generated by Django 5.0.3 on 2024-03-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_text_student_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='author_name',
            field=models.CharField(blank=True, help_text='Author name', max_length=100, null=True, verbose_name='Author name'),
        ),
        migrations.AddField(
            model_name='text',
            name='source_type',
            field=models.CharField(blank=True, help_text='Source type', max_length=100, null=True, verbose_name='Source type'),
        ),
    ]
