# Generated by Django 5.0.3 on 2024-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_text_author_name_text_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='sex',
            field=models.CharField(choices=[(None, ''), ('M', 'Male'), ('F', 'Female')], help_text='Student sex', max_length=1, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='text',
            name='type',
            field=models.CharField(choices=[(None, ''), ('SPOKEN', 'Spoken'), ('WRITTEN', 'Written'), ('NOTEBOOKS', 'Notebooks')], help_text='Type of the text', max_length=10, verbose_name='Type'),
        ),
    ]
