# Generated by Django 5.0.3 on 2024-04-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_text_sex_alter_text_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='words_indexed',
            field=models.BooleanField(default=False, editable=False, help_text='Indicates whether the words of this text are indexed or not', verbose_name='Words indexed'),
        ),
    ]
