# Generated by Django 5.0.3 on 2024-04-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_text_sex_alter_text_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Content of the functional word', max_length=10, unique=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Functional Word',
                'verbose_name_plural': 'Functional Words',
            },
        ),
    ]
