# Generated by Django 5.0.3 on 2024-04-17 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_text_author_name_alter_text_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the announcement', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of the announcement', null=True, verbose_name='Description')),
                ('image_link', models.URLField(blank=True, help_text='Link to the image of the announcement', null=True, verbose_name='Image link')),
                ('link', models.URLField(blank=True, help_text='Link to the announcement', null=True, verbose_name='Link')),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of adding the announcement', verbose_name='Added on')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the announcement is shown or not', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ('-posted_on',),
            },
        ),
    ]
