# Generated by Django 5.0.4 on 2024-04-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Term in the dictionary', max_length=50, verbose_name='Term')),
                ('definition', models.TextField(help_text='Definition of the term', verbose_name='Definition')),
            ],
            options={
                'verbose_name': 'Dictionary Definition',
                'verbose_name_plural': 'Dictionary Definitions',
            },
        ),
    ]
