# Generated by Django 5.0.3 on 2024-04-19 01:41
from pathlib import Path

from django.db import migrations
from openpyxl import load_workbook, Workbook
from openpyxl.worksheet.worksheet import Worksheet


def import_from_excel_files(apps, schema_editor):
    DictionaryDefinition = apps.get_model('main', 'DictionaryDefinition')
    for excel_filepath in (Path(__file__).parent / 'dictionary').glob('*.xlsx'):
        wb: Workbook = load_workbook(excel_filepath, read_only=True, data_only=True)
        sheet: Worksheet = wb.active
        definitions = []
        for row in sheet.iter_rows(values_only=True):
            definitions.append(DictionaryDefinition(term=row[0], definition=row[1]))
        DictionaryDefinition.objects.bulk_create(definitions)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_dictionarydefinition'),
    ]

    operations = [
        migrations.RunPython(import_from_excel_files)
    ]
