# Generated by Django 5.0.4 on 2024-04-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_fill_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='bigrams_indexed',
            field=models.BooleanField(default=False, editable=False, help_text='Indicates whether the bigrams of this text are indexed or not', verbose_name='Bigrams indexed'),
        ),
    ]
