# Generated by Django 5.0.6 on 2024-06-27 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_fill_affixes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(db_default=1, help_text='Owner of the blog', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='blog',
            name='public',
            field=models.BooleanField(db_default=True, help_text='Indicates whether the blog is public or not', verbose_name='Public'),
        ),
    ]
