# Generated by Django 5.0.7 on 2024-07-16 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorphologicalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Symbol of the tag (You can use only letters, numbers, and underscores)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\w+$')], verbose_name='Symbol')),
                ('content', models.TextField(help_text='Content of the tag', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Morphological Tag',
                'verbose_name_plural': 'Morphological Tags',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemanticTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Symbol of the tag (You can use only letters, numbers, and underscores)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\w+$')], verbose_name='Symbol')),
                ('content', models.TextField(help_text='Content of the tag', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Semantic Tag',
                'verbose_name_plural': 'Semantic Tags',
                'abstract': False,
            },
        ),
    ]
