# Generated by Django 5.0.7 on 2024-07-16 11:10

from django.contrib.auth import get_user_model
from django.db import migrations


def add_permissions(apps, schema_editor):
    from guardian.shortcuts import assign_perm
    for staff_user in get_user_model().objects.filter(is_staff=True, is_superuser=False):
        assign_perm('main.add_semantictag', staff_user)
        assign_perm('main.view_semantictag', staff_user)
        assign_perm('main.change_semantictag', staff_user)
        assign_perm('main.delete_semantictag', staff_user)
        assign_perm('main.add_morphologicaltag', staff_user)
        assign_perm('main.view_morphologicaltag', staff_user)
        assign_perm('main.change_morphologicaltag', staff_user)
        assign_perm('main.delete_morphologicaltag', staff_user)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_morphologicaltag_semantictag'),
        ('guardian', '0002_generic_permissions_index'),
    ]

    operations = [
        migrations.RunPython(add_permissions, reverse_code=migrations.RunPython.noop),
    ]
