# Generated by Django 5.0.7 on 2024-07-23 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_add_permissions_on_tag_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morphologicaltag',
            name='symbol',
            field=models.CharField(help_text='Symbol of the tag (You can use only English letters, numbers, and underscores)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$')], verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='semantictag',
            name='symbol',
            field=models.CharField(help_text='Symbol of the tag (You can use only English letters, numbers, and underscores)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_]+$')], verbose_name='Symbol'),
        ),
    ]
