# Generated by Django 5.0.3 on 2024-04-01 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0009_alter_text_sex_alter_text_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(help_text='Number of times this word appears in this text', verbose_name='Frequency')),
                ('text', models.ForeignKey(help_text='Text that contains this word', on_delete=django.db.models.deletion.CASCADE, related_name='text_words', to='main.text', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Text Word',
                'verbose_name_plural': 'Text Words',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Word that is found in texts', max_length=50, verbose_name='Word')),
                ('texts', models.ManyToManyField(help_text='Texts that contain this word', through='indexes.TextWord', to='main.text', verbose_name='Texts')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.AddField(
            model_name='textword',
            name='word',
            field=models.ForeignKey(help_text='Word that is found in this text', on_delete=django.db.models.deletion.CASCADE, related_name='text_words', to='indexes.word', verbose_name='Word'),
        ),
    ]
