# Generated by Django 5.0.3 on 2024-04-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0001_initial'),
        ('main', '0011_alter_text_sex_alter_text_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(help_text='Word that is found in texts', max_length=50, unique=True, verbose_name='Word'),
        ),
        migrations.AlterUniqueTogether(
            name='textword',
            unique_together={('text', 'word')},
        ),
    ]
