# Generated by Django 5.0.3 on 2024-04-06 06:16
import logging

from django.db import migrations

logger = logging.getLogger('django.migrations')


def migrate_to_whole_tokens(apps, schema_editor):
    TextWord = apps.get_model('indexes', 'TextWord')
    Token = apps.get_model('indexes', 'Token')
    TextToken = apps.get_model('indexes', 'TextToken')
    start = 0
    end = 0
    token_content = ''
    count = TextWord.objects.count()
    i = 1
    for text_word in TextWord.objects.all():
        if text_word.start == start and text_word.end == end:
            token_content += text_word.word.content
        elif token_content:
            token, created = Token.objects.get_or_create(content=token_content)
            TextToken.objects.get_or_create(text=text_word.text, token=token, start=start, end=end)
            logger.info(
                '(%d/%d) Token migrated: %s [%d:%d] from "%s"',
                i, count, token_content, start, end, text_word.text
            )
            i += 1
            start = text_word.start
            end = text_word.end
            token_content = text_word.word.content


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0002_texttoken_token_texttoken_token_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_to_whole_tokens, reverse_code=migrations.RunPython.noop)
    ]
