# Generated by Django 5.0.3 on 2024-04-07 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0002_texttoken_token_texttoken_token_and_more'),
        ('main', '0011_alter_text_sex_alter_text_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='texttoken',
            unique_together={('text', 'start', 'end')},
        ),
    ]
