# Generated by Django 5.0.3 on 2024-04-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0003_alter_texttoken_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='texts',
        ),
        migrations.DeleteModel(
            name='TextWord',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
