# Generated by Django 5.0.4 on 2024-04-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0004_remove_word_texts_delete_textword_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text_token', models.ForeignKey(help_text='First text token of the bigram', on_delete=django.db.models.deletion.CASCADE, related_name='first_bigrams', to='indexes.texttoken', verbose_name='First Text Token')),
                ('second_text_token', models.ForeignKey(help_text='Second text token of the bigram', on_delete=django.db.models.deletion.CASCADE, related_name='second_bigrams', to='indexes.texttoken', verbose_name='Second Text Token')),
            ],
            options={
                'verbose_name': 'Bigram',
                'verbose_name_plural': 'Bigrams',
                'unique_together': {('first_text_token', 'second_text_token')},
            },
        ),
    ]
