# Generated by Django 5.0.4 on 2024-04-29 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0004_remove_word_texts_delete_textword_delete_word'),
        ('main', '0017_text_bigrams_indexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bigram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(default=0, help_text='Number of occurrences of the bigram in the text', verbose_name='Frequency')),
                ('first_token', models.ForeignKey(help_text='First token of the bigram', on_delete=django.db.models.deletion.CASCADE, related_name='first_bigrams', to='indexes.token', verbose_name='First Token')),
                ('second_token', models.ForeignKey(help_text='Second token of the bigram', on_delete=django.db.models.deletion.CASCADE, related_name='second_bigrams', to='indexes.token', verbose_name='Second Token')),
                ('text', models.ForeignKey(help_text='Text that contains this bigram', on_delete=django.db.models.deletion.CASCADE, related_name='bigrams', to='main.text', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Bigram',
                'verbose_name_plural': 'Bigrams',
                'unique_together': {('first_token', 'second_token', 'text')},
            },
        ),
    ]
