# Generated by Django 5.0.4 on 2024-04-29 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0005_bigram'),
        ('main', '0018_text_trigrams_indexed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trigram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.PositiveIntegerField(default=0, help_text='Number of occurrences of the trigram in the text', verbose_name='Frequency')),
                ('first_token', models.ForeignKey(help_text='First token of the trigram', on_delete=django.db.models.deletion.CASCADE, related_name='first_trigrams', to='indexes.token', verbose_name='First Token')),
                ('second_token', models.ForeignKey(help_text='Second token of the trigram', on_delete=django.db.models.deletion.CASCADE, related_name='second_trigrams', to='indexes.token', verbose_name='Second Token')),
                ('text', models.ForeignKey(help_text='Text that contains this trigram', on_delete=django.db.models.deletion.CASCADE, related_name='trigrams', to='main.text', verbose_name='Text')),
                ('third_token', models.ForeignKey(help_text='Third token of the trigram', on_delete=django.db.models.deletion.CASCADE, related_name='third_trigrams', to='indexes.token', verbose_name='Third Token')),
            ],
            options={
                'verbose_name': 'Trigram',
                'verbose_name_plural': 'Trigrams',
                'unique_together': {('first_token', 'second_token', 'third_token', 'text')},
            },
        ),
    ]
